### ISSUE TITLE
forward doesn't work

### ISSUE THREAD

**Issue by mosesoak** [plrenaudin/goto-last-edit-vscode#1]
I'm using vs code insiders edition, and don't have any conflicting keyboard shortcuts set up. Back works but forward does not

**Comment by mosesoak** [comment]
Hm, I'm on MacOS and I just got a weird behavior that might relate to the above, tried to zoom in/out using cmd+-/= and was getting navigation, including forward. That seemed buggy though so I restarted and was back to those keys doing zoom, and only ctrl+- working for navigation.

**Comment by plrenaudin** [comment]
Thank you for logging this, unfortunately I don't own a Mac myself to try to reproduce this.
Can you tell me if `cmd =` and `cmd -` work for navigation after you restarted?
I hope it's just a matter of key binding.

**Comment by TrevorSayre** [comment]
@plrenaudin I was having this issue as well for `ctrl+=` but `cmd+=` does work for *next edit*, as does `cmd+-` for *last edit* so long as I stay in that file.

**Comment by plrenaudin** [comment]
Thanks for your help,
I updated the readme to show the MacOS keys (I forgot to put them in it originally)
