### ISSUE TITLE
Switch to a different file and back loses history

### ISSUE THREAD

**Issue by TrevorSayre** [plrenaudin/goto-last-edit-vscode#2]
If I make an edit on one line, then go to another line in the same file and make an edit, I can easily toggle back and forth between the edits with `cmd+-` and `cmd+=`.

However, if I go to another file (tab) and return to the original file, that edit history seems to be gone. Instead the previous edit command just puts me at the top of the file.

**Comment by plrenaudin** [comment]
This is now fixed, thanks for opening this bug!
