### ISSUE TITLE
Rename keybindings commands

### ISSUE THREAD

**Issue by DonSkeleton** [plrenaudin/goto-last-edit-vscode#3]
Hey,

right know the keybindings for your extension are called "extension.goBack" and "extension.goForward". 
I think it would be better to use your extension name instead of just "extension", so:
"gotoLastEdit.goBack"
"gotoLastEdit.goForward"

Most extensions seem to use this as the naming convention of their keybindings. 

I would also recommend you post the keybinding names on the [extension page](https://marketplace.visualstudio.com/items?itemName=plrenaudin.gotolastedit) so people know how to change the keybindings without having to look into the extension files.

Thanks for the extension :-)

**Comment by plrenaudin** [comment]
Hello,

Thanks for the feedback!

This is fixed with this commit: https://github.com/plrenaudin/goto-last-edit-vscode/commit/caad61ad92001fce91146f3ca8eddfe1bc5ac359
